import test from 'node:test';
import assert from 'node:assert/strict';
import { validateMonetization, resolveAd } from '../../src/lib/monetization.mjs';
const base=()=>({provider:'none',adsense:{client:'',slots:{home:'',article:''},adsTxt:''},banners:{home:{title:'',description:'',url:'',image:'',imageAlt:''},article:{title:'',description:'',url:'',image:'',imageAlt:''}}});
test('disabled mode hides all configured placements',()=>{const c=base();c.banners.home={title:'テスト',description:'',url:'https://example.com/',image:'',imageAlt:''};validateMonetization(c);assert.equal(resolveAd(c,'home'),null);assert.equal(resolveAd(c,'article'),null);});
test('banner mode renders only configured placement',()=>{const c=base();c.provider='banner';c.banners.home={title:'テスト広告',description:'テスト',url:'https://example.com/',image:'',imageAlt:''};validateMonetization(c);assert.equal(resolveAd(c,'home').type,'banner');assert.equal(resolveAd(c,'article'),null);});
test('rejects executable URLs and invalid image paths',()=>{for(const url of ['javascript:alert(1)','http://example.com','https://user:password@example.com']){const c=base();c.banners.home.url=url;assert.throws(()=>validateMonetization(c));}const c=base();c.banners.home.image='/ads/../secret.png';assert.throws(()=>validateMonetization(c));});
test('adsense requires valid account and at least one unit',()=>{const c=base();c.provider='adsense';assert.throws(()=>validateMonetization(c));c.adsense.client='ca-pub-1234567890123456';assert.throws(()=>validateMonetization(c));c.adsense.slots.home='1234567890';validateMonetization(c);assert.equal(resolveAd(c,'home').slot,'1234567890');assert.equal(resolveAd(c,'article'),null);});
test('ads.txt must match configured publisher',()=>{const c=base();c.adsense.client='ca-pub-1234567890123456';c.adsense.adsTxt='google.com, pub-1234567890123456, DIRECT, f08c47fec0942fa0';validateMonetization(c);c.adsense.adsTxt='google.com, pub-0000000000000000, DIRECT, f08c47fec0942fa0';assert.throws(()=>validateMonetization(c));});
